version: "3"

services:
  ocserv:
    container_name: ocserv
    image: morganonbass/ocserv-saml:latest
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      HOSTNAME: vpn.example.com
      LISTEN_PORT: 443
      TUNNEL_MODE: 'split_include'
      TUNNEL_ROUTES: '10.1.0.0/25, 192.168.69.0/24'
      DNS_SERVERS: 192.168.1.1
      DEFAULT_DOMAIN: 'internal.example.com'
      SPLIT_DNS_DOMAINS: 'internal.example.com'
      CLIENTNET: 192.168.248.0
      CLIENTNETMASK: 255.255.255.128
    volumes:
      - './config/:/config/'
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: unless-stopped
